
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const AdminPage = lazy(() => import("./pages/AdminPage.tsx"));
const AnalyticsPage = lazy(() => import("./pages/AnalyticsPage.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const MyCryptoPage = lazy(() => import("./pages/MyCryptoPage.tsx"));
const ProfilePage = lazy(() => import("./pages/ProfilePage.tsx"));
const SignupPage = lazy(() => import("./pages/SignupPage.tsx"));
const TaxReportsPage = lazy(() => import("./pages/TaxReportsPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/admin-page", element: <UserGuard><AdminPage /></UserGuard>},
	{ path: "/adminpage", element: <UserGuard><AdminPage /></UserGuard>},
	{ path: "/analytics-page", element: <UserGuard><AnalyticsPage /></UserGuard>},
	{ path: "/analyticspage", element: <UserGuard><AnalyticsPage /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/login", element: <UserGuard><Login /></UserGuard>},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/my-crypto-page", element: <UserGuard><MyCryptoPage /></UserGuard>},
	{ path: "/mycryptopage", element: <UserGuard><MyCryptoPage /></UserGuard>},
	{ path: "/profile-page", element: <UserGuard><ProfilePage /></UserGuard>},
	{ path: "/profilepage", element: <UserGuard><ProfilePage /></UserGuard>},
	{ path: "/signup-page", element: <UserGuard><SignupPage /></UserGuard>},
	{ path: "/signuppage", element: <UserGuard><SignupPage /></UserGuard>},
	{ path: "/tax-reports-page", element: <UserGuard><TaxReportsPage /></UserGuard>},
	{ path: "/taxreportspage", element: <UserGuard><TaxReportsPage /></UserGuard>},

];
